### ISSUE TITLE
Ajouter le programme de formation à la présentation détaillée de la formation

### ISSUE THREAD

**Issue by yaf** [descodeuses/descodeuses.github.io#16]
_À ajouter dans #9_

Programme de la formation :

- Préciser objectifs pédagogiques
- Modalités pédagogiques et méthodes pédagogiques
- Approche par compétences
- Ajouter partie “moyens de suivi et d’appréciation des résultats” de StraFormation
- Modalités d’évaluation

**Comment by Emilie-Rose** [comment]
ajout du "contenu de la formation" dans formations/developpeuse-web/index.html

**Comment by yaf** [comment]
Super !

**Comment by Emilie-Rose** [comment]
par contre la partie "Ajouter partie « moyens de suivi et d'appréciation des résultats » de StraFormation" n'est pas faite je ne sais pas ce qu'il faut renseigner

**Comment by yaf** [comment]
Merci pour la précision. Je pense que si c'est important, ça apparaitra plus tard. On laisse comme ça et on verra.
