### ISSUE TITLE
Télécharger le programme de formation

### ISSUE THREAD

**Issue by yaf** [descodeuses/descodeuses.github.io#17]
Avoir un PDF téléchargeable du programme de la formation développeuse web #9 .

**Comment by Emilie-Rose** [comment]
lien telechargeable mais probleme avec l'icon

**Comment by yaf** [comment]
Super ! Je ferme le ticket alors.

Peut-être faut-il en ajouter un nouveau pour l'icone ?

**Comment by Emilie-Rose** [comment]
Suppression du programme et en attente de la brochure  mise à jour pour le lien téléchargeable!
