### ISSUE TITLE
Contact et accessibilité pour la formation développeuse web

### ISSUE THREAD

**Issue by yaf** [descodeuses/descodeuses.github.io#19]
Ajouter les informations à propos de l'accessibilité de la formation (nous parlons bien ici d'accessibilité au sens [RGAA](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/)).

- Préciser l'accessibilité → voir fichier programme de formation
- Adresse mail dédié aux personnes en situation de handicap pour contact
- N° de téléphone pour contact
- Nom du référent handicap

Ces informations sont à ajouter avec la formation (dans la page formation ou bien une sous page formation...). Ce ne sont pas les informations sur l'accessibilité du site des descodeuses.

**Comment by Emilie-Rose** [comment]
ajout: 
- Préciser l'accessibilité → voir fichier programme de formation
- Adresse mail dédiée aux personnes en situation de handicap contact
- N° de téléphone pour contact
- Nom du référent handicap
mais voir si il ne faut pas ajouter de contenu???

**Comment by Emilie-Rose** [comment]
A quel niveau ajouter la page contact: formation? ou autres?

**Comment by yaf** [comment]
Pas besoin d'ajouter du contenu pour le moment. Poser ces éléments-là, nous verrons ensuite.

Il n'y a pas de page contact à ajouter. Ce sont des informations liées à la formation. Je vais préciser dans le ticket.

Merci pour ces questions. J'espère y avoir répondu @Emilie-Rose ?

**Comment by yaf** [comment]
Ce sont des informations d'accessibilité lié à la formation, pas au site. C'est à ajouter dans la fiche « détaillée » de la formation
