### ISSUE TITLE
Inscription à la formation en tant qu'apprenante clairement identifié

### ISSUE THREAD

**Issue by yaf** [descodeuses/descodeuses.github.io#2]

**Comment by saphirkoeum** [comment]
Ajouter un moyen pour s'incrire : 
Formulaire sur le site ou formulaire google ?

**Comment by yaf** [comment]
Il faut pouvoir s'inscrire.

Utiliser le formulaire https://docs.google.com/forms/d/e/1FAIpQLSfTA-C1Tjmpd9Xyr98w13FLg_wLgT0HAzf8gEVIgw2krHyyEQ/viewform?usp=sf_link

On le changera peut-être plus tard, c'est à voir
