### ISSUE TITLE
Pouvoir aller au code source

### ISSUE THREAD

**Issue by yaf** [descodeuses/descodeuses.github.io#26]
Descodeuses c'est une association dans laquelle on parle souvent de programmation. Ça serait intéressant d'avoir un lien vers le code source du site.

**Comment by Emilie-Rose** [comment]
par ex : view-source:https://descodeuses.github.io/ ou ctrl+u  ?

**Comment by yaf** [comment]
Non, je pensais à un lien vers le repo github.

**Comment by Emilie-Rose** [comment]
ajout lien github dans le footer de 'defaut.html' =>       <p><a href="/https://descodeuses.github.io/">github</a></p>

**Comment by yaf** [comment]
Il faudrait un lien qui pointe vers https://github.com/descodeuses

**Comment by Emilie-Rose** [comment]
lien corrigé
