### ISSUE TITLE
Expliquer le processus de sélection

### ISSUE THREAD

**Issue by yaf** [descodeuses/descodeuses.github.io#8]

**Comment by yaf** [comment]
Il reste une faute d'orthographe

**Comment by yaf** [comment]
Ce sont des informations liées à la formation, pas au site. C'est à ajouter dans la fiche « détaillée » de la formation

**Comment by yaf** [comment]
C'est à positionner dans la fiche détailler de la formation

**Comment by saphirkoeum** [comment]
A rajouter comme sous menu du lien Formation

**Comment by saphirkoeum** [comment]
Afficher le contenue dans formation et pas en sous dossier
